### ISSUE TITLE
Promises v3 Checklist

### ISSUE THREAD

**Issue by valzargaming** [discord-php/DiscordPHP#1149]
Per https://github.com/reactphp/promise/releases/tag/v3.0.0

Irrelevant:
- [x] Existing instances of FulfilledPromise and RejectedPromise classes must be updated to use resolve() and reject() functions instead
- [x] Existing instances of LazyPromise should be removed
- [x] Any instances of some(), map(), and reduce() functions must be replaced with the any() or all() functions (I don't think we use these)

Breaking changes:
- [x] #1150 - Instances of existing code explicitly typecasting ExtendedPromiseInterface should be removed.
- [x] #1151 - Instances of existing code need to call resolve or reject and handle errors appropriately.
- [x] #1152 - Instances of existing code need to be replaced with then and resolved.

Non-breaking changes:
- [x] otherwise() and always() are deprecated, replaced by catch() and finally() (only instance I could find was [Discord.php](https://github.com/discord-php/DiscordPHP/blob/9fab769aa47a57052f6fa0309bcede6abe81e0ca/src/Discord/Discord.php#L518))

**Comment by key2peace** [comment]
All this should be in https://github.com/discord-php/DiscordPHP/tree/promise-v3 now

**Comment by valzargaming** [comment]
ExtendedPromiseInterface extends PromiseInterface, and Promise v2 implements ExtendedPromiseInterface, so instead of replacing the existing typehinting to PromiseInterface we _could_ just use React\Promise\Promise, which would overcome the hurdle and be better for futureproofing code. This seems to be the ReactPHP developers' intent as well, given they have made all classes final to encourage composition.

**Comment by shehi** [comment]
It's painful to read this @valzargaming  :) Code-ify more please.

**Comment by valzargaming** [comment]
> It's painful to read this @valzargaming :) Code-ify more please.

This is already coded in the promises v3 branch as of today.

**Comment by 2colours** [comment]
What's the state of this issue?

**Comment by valzargaming** [comment]
We will not be updating to promises v3 until our dependencies can support
it. The only alternative would be to rewrite all of those dependencies
ourselves, going through the composer requirements one at a time to find
them, manually recreate them with the changes, and then maintain them going
forward, which is not something we are willing to commit to at this time.

**Comment by 2colours** [comment]
I couldn't resist going through the "bottleneck" dependencies:

- discord-php/http (constraint: ^2.2)
  - this is under your control
- react/datagram (constraint:  ~2.1)
  - DiscordPHP directly depends on an outdated version (1.5) of this library
  - DiscordPHP itself should be updated to a more recent version that does support more recent versions of react/promise

That's all I can see with `composer show --tree`. It doesn't seem like there is any external blocker - in fact, the biggest blocker is the direct dependency on another outdated react package (react/datagram). Maybe the issue should be about upgrading react/datagram, then.

**Comment by valzargaming** [comment]
> **UPDATE:** Sorry, this was for v7. For v10, react/datagram _is_ upgraded and the only problem is the _direct_ dependency on v2 in your own package discord-php/http.

@2colours, thanks for checking and confirming this! I announced on 9/25/2024 in our [Discord](https://discord.gg/dphp) that we have officially discontinued v7 support specifically for reasons like this along with [Discord having marked the v7 gateway as deprecated](https://discord.com/developers/docs/reference#api-versioning). We will not take into consideration any issues with that older version when working on this future update.

**Comment by 2colours** [comment]
> wyrihaximus/react-cache-redis still relies on react/promise ^2.8 and is the biggest change to the v10 release.

The two most recent versions of that package do support v3 Promises (the latest version, 4.5.0 at this moment, only supports that).
 
But anyway, most importantly, this is just a dev dependency. A dev dependency really shouldn't poison downstream users; I don't know how Composer works under the hood but it rather sounds like their issue if this can happen at all.

> I announced on 9/25/2024 in our [Discord](https://discord.gg/dphp) that we have officially discontinued v7 support specifically for reasons like this along with [Discord having marked the v7 gateway as deprecated](https://discord.com/developers/docs/reference#api-versioning).

You mean, the server I was banned from while trying to clarify https://github.com/discord-php/DiscordPHP/pull/1208, why it's a library issue and not a "you problem" to swallow promise rejections, for mere ego reasons in my opinion? That's too bad, especially that this is a general purpose PHP Discord, not just a Discord for your library. Give people power to see their true nature...

**Comment by valzargaming** [comment]
> > wyrihaximus/react-cache-redis still relies on react/promise ^2.8 and is the biggest change to the v10 release.
> But anyway, most importantly, this is just a dev dependency. A dev dependency really shouldn't poison downstream users; I don't know how Composer works under the hood but it rather sounds like their issue if this can happen at all.

You seem to have misunderstood the context here. The inclusion of the experimental interface is intentional and serves to notify developers of its experimental nature. This is why it’s currently restricted to dev usage, it’s not yet considered stable. While we originally planned to launch the stable version with v10, we chose to delay it to ensure its readiness.

> You mean, the server I was banned from while trying to clarify #1208, why it's a library issue and not a "you problem" to swallow promise rejections, for mere ego reasons in my opinion? That's too bad, especially that this is a general purpose PHP Discord, not just a Discord for your library. Give people power to see their true nature...

This issue appears to be more about individual circumstances than the library itself. If you’d like to revisit the situation, you’re welcome to submit an unban request to maintainers@discordphp.org for review and explain why you were banned and why it should be lifted. Be sure to included your discord username or id.
